# Generated by Django 2.1 on 2018-08-20 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 20, 0, 17, 6, 89699, tzinfo=utc))),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pic_folder/imgs/')),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=100)),
                ('manual', models.FileField(blank=True, null=True, upload_to='file_folder/manual')),
                ('min_best_for', models.IntegerField(default=0)),
                ('max_best_for', models.IntegerField(default=100)),
                ('difficulty_level', models.CharField(choices=[('very_easy', 'muito fácil'), ('easy', 'facil'), ('normal', 'normal'), ('hard', 'difícil'), ('very_hard', 'muito difícil')], max_length=25)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameXGameMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Game')),
                ('game_mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.GameMechanism')),
            ],
        ),
    ]
