# Generated by Django 2.1 on 2018-08-20 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180820_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 0, 34, 22, 883116, tzinfo=utc)),
        ),
    ]
